{{ if .kong.enabled -}}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ingress-kong
  namespace: infrastructure
spec:
  interval: 60m
  releaseName: ingress-kong
  chart:
    spec:
      chart: ingress-kong
      version: 0.13.1 
      sourceRef:
        kind: HelmRepository
        name: ingress-kong
      interval: 10m
  values:
    controller:
      {{- if .linkerd.enabled }}
      admissionWebhooks:
        patch:
          podAnnotations:
            linkerd.io/inject: disabled
      podAnnotations:
        linkerd.io/inject: disabled
      {{- end }}
      {{- if not .civo.enabled }}
      service:
        externalTrafficPolicy: Local
      {{- end }}
      {{- if eq (default "" .vendor) "do" }}
      annotations:
        service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
        service.beta.kubernetes.io/do-loadbalancer-hostname: "{{ .nginx.host }}"
      config:
        use-proxy-protocol: "true"
      {{- end }}
      metrics:
        enabled: true
        service:
          annotations:
            prometheus.io/port: "10254"
            prometheus.io/scrape: "true"
      defaultBackend:
        enabled: true
        replicaCount: 2
{{- end }}
